version: '3.3'

services:
  crm-db:
    image: mysql:5.7
    container_name: crm-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'crm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    ports:
      - 3307:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  
volumes:
  my-db: